version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - breeze-predictor-dependencies-{{ checksum "package.json" }}
            - breeze-predictor-dependencies-
      - run:
          command: npm i
          name: Install dependencies
      - save_cache:
          key: breeze-predictor-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: npm run lint
          name: Lint code

  unit-test:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - breeze-predictor-dependencies-{{ checksum "package.json" }}
            - breeze-predictor-dependencies-
      - attach_workspace:
          at: ~/repo
      - run:
          command: npm run test:ci
          name: Unit test

  sonarqube:
    docker:
      - image: breezejs/sonar-scanner:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - breeze-predictor-dependencies-{{ checksum "package.json" }}
            - breeze-predictor-dependencies-
      - attach_workspace:
          at: ~/repo
      - run:
          command: sonar-scanner -Dsonar.projectKey=breezejs_predictor -Dsonar.organization=breezejs -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
          name: Static code analysis

  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - breeze-predictor-dependencies-{{ checksum "package.json" }}
            - breeze-predictor-dependencies-
      - attach_workspace:
          at: ~/repo
      - run:
          command: npm run build
          name: Build

workflows:
  version: 2

  test-and-build:
    jobs:
      - setup
      - sonarqube:
          requires:
            - setup
      - unit-test:
          requires:
            - setup
      - build:
          requires:
            - unit-test
